# Generated by Django 5.0.7 on 2026-08-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='a_utilise_essai_gratuit',
            field=models.BooleanField(default=False, help_text="Un utilisateur ne peut bénéficier de l'essai gratuit de 14 jours que sur le tout premier salon qu'il crée, même s'il crée ensuite d'autres salons."),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='mot_de_passe_temporaire',
            field=models.BooleanField(default=False, help_text="Vrai quand le compte a été créé par un gestionnaire pour un employé : l'utilisateur doit changer son mot de passe à sa première connexion."),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_url',
            field=models.URLField(blank=True, help_text="Photo de profil. Stockée en tant qu'URL (voir README pour le stockage objet à brancher).", null=True),
        ),
    ]
