# Generated by Django 5.0.7 on 2026-08-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='duree_mois',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
