# Generated by Django 5.0.7 on 2026-08-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_alter_abonnement_duree_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='nom_modifiable',
            field=models.BooleanField(default=True, help_text="Devient faux dès que le propriétaire a renommé le salon une fois après sa création — le nom n'est alors plus modifiable via l'API."),
        ),
        migrations.AddField(
            model_name='salon',
            name='photo_url',
            field=models.URLField(blank=True, help_text="Photo du salon. Stockée en tant qu'URL (voir README pour le stockage objet à brancher).", null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='duree_mois',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
