# Generated by Django 5.0.7 on 2026-08-29 08:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_salon_nom_modifiable_salon_photo_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type_forfait', models.CharField(choices=[('abonnement_salon', 'Abonnement salon'), ('analyse_sectorielle', 'Analyse sectorielle'), ('autre', 'Autre')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_mois', models.PositiveSmallIntegerField(blank=True, help_text="Laisser vide si le forfait n'est pas périodique (ex. analyse sectorielle).", null=True)),
                ('avantages', models.JSONField(blank=True, default=list, help_text='Liste de courtes phrases affichées comme avantages sur la landing page.')),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forfaits_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordre_affichage', 'prix'],
            },
        ),
    ]
