# Generated by Django 5.0.7 on 2026-08-29 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_forfait'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codesponsoring',
            name='beneficiaire_utilisateur',
            field=models.ForeignKey(blank=True, help_text='Renseigné uniquement pour les codes achetés via le programme partenaire employé.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_sponsoring_achetes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codesponsoring',
            name='commission_fixe_par_utilisation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='codesponsoring',
            name='est_partenaire_employe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codesponsoring',
            name='nombre_utilisations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codesponsoring',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='codesponsoring',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_sponsoring_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
