# Generated by Django 5.0.7 on 2026-08-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_codesponsoring_beneficiaire_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesponsoring',
            name='date_paiement_confirme',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesponsoring',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('carte_bancaire', 'Carte bancaire')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='codesponsoring',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('en_attente_paiement', 'En attente de paiement')], default='actif', max_length=25),
        ),
        migrations.AlterField(
            model_name='salon',
            name='photo_url',
            field=models.TextField(blank=True, help_text="Photo du salon : soit une URL externe, soit une image encodée en base64 (data:image/...;base64,...) envoyée directement depuis le formulaire d'upload du frontend. Un TextField plutôt qu'un URLField pour accepter les deux cas — voir README pour un branchement vers un vrai stockage objet (S3/Cloudinary) en production à grande échelle.", null=True),
        ),
    ]
