# Generated by Django 5.0.7 on 2026-08-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_codesponsoring_date_paiement_confirme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereduction',
            name='nombre_utilisations',
            field=models.PositiveIntegerField(default=0, help_text='Compteur incrémenté à chaque abonnement souscrit avec ce code.'),
        ),
    ]
