# Generated by Django 5.0.7 on 2026-09-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_codereduction_nombre_utilisations'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereduction',
            name='proprietaire_contact',
            field=models.CharField(blank=True, help_text='Email ou téléphone du propriétaire du code.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='codereduction',
            name='proprietaire_nom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
