# Generated by Django 5.0.7 on 2026-09-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_codereduction_proprietaire_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codereduction',
            name='pourcentage_reduction',
        ),
        migrations.AddField(
            model_name='codereduction',
            name='montant_reduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant fixe (en FCFA) déduit du montant total, et non un pourcentage.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codesponsoring',
            name='montant_reduction_utilisateur',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Montant fixe (en FCFA) déduit du montant total de l'abonnement pour la personne qui utilise ce code à la souscription/au renouvellement — distinct de la commission versée au propriétaire du code.", max_digits=10),
        ),
    ]
