# Generated by Django 5.0.7 on 2026-08-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('materiel', 'Matériel'), ('produit_homme', 'Produit homme'), ('produit_femme', 'Produit femme'), ('esthetique', 'Esthétique'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
