# Generated by Django 5.0.7 on 2026-08-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneticket',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé (soin réalisé)'), ('annule', 'Annulé (client absent/annulation)')], default='en_attente', max_length=20),
        ),
    ]
