# Generated by Django 5.0.7 on 2026-08-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ligneticket_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='montant_brut',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='montant_net',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reduction_pourcentage',
            field=models.IntegerField(default=0),
        ),
    ]
