# Generated by Django 5.0.7 on 2026-08-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_montant_brut_alter_ticket_montant_net_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='montant_brut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='montant_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reduction_pourcentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
