# Generated by Django 5.0.7 on 2026-09-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_montant_brut_alter_ticket_montant_net_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneticket',
            name='prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='montant_brut',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='montant_net',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reduction_pourcentage',
            field=models.IntegerField(default=0),
        ),
    ]
