# Generated by Django 5.0.7 on 2026-08-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='peut_confirmer_ticket',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='peut_creer_ticket',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='peut_valider_ticket',
            field=models.BooleanField(default=True),
        ),
    ]
